# Generated by Django 3.2.4 on 2021-06-26 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twofactorauthenticationsession',
            name='answer_verified',
        ),
        migrations.RemoveField(
            model_name='twofactorauthenticationsession',
            name='questions_attempted',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('django_user', 'question')},
        ),
    ]
